### ISSUE TITLE
Fail on start

### ISSUE THREAD

**Issue by vvscode** [devmanorg/fiasko_bro#120]
`python3` (Python 3.7.2)

```>>> from fiasko_bro import validate
/usr/local/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'validate' from 'fiasko_bro' (/usr/local/lib/python3.7/site-packages/fiasko_bro/__init__.py)
```

pip3 list shows me `Fiasko-Bro       0.0.1.1`

what can I do to run it locally?

Thanks in advance

**Comment by vvscode** [comment]
Installation passes with logs:

```bash
 pip3 install fiasko_bro --force
Collecting fiasko_bro
  Using cached https://files.pythonhosted.org/packages/5e/3c/546e36aac1ed2d2883c3f47d25473375a43a4b2dc2f988d1dfb90aea246a/Fiasko_Bro-0.0.1.1-py2.py3-none-any.whl
Collecting pep8==1.7.1 (from fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/42/3f/669429ce58de2c22d8d2c542752e137ec4b9885fff398d3eceb1a7f5acb4/pep8-1.7.1-py2.py3-none-any.whl
Collecting mccabe==0.6.1 (from fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting pytest-cov==2.5.1 (from fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/30/7d/7f6a78ae44a1248ee28cc777586c18b28a1df903470e5d34a6e25712b8aa/pytest_cov-2.5.1-py2.py3-none-any.whl
Collecting Babel==2.5.3 (from fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/94/03/14e68ad12e771a79cf96792f7158d68a7b3d8c7b2badf39e9ef1f65b57d6/Babel-2.5.3-py2.py3-none-any.whl
Collecting codecov==2.0.15 (from fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/8b/28/4c1950a61c3c5786f0f34d643d0d28ec832433c9a7c0bd157690d4eb1d5f/codecov-2.0.15-py2.py3-none-any.whl
Collecting GitPython==2.0.8 (from fiasko_bro)
Collecting pytest==3.4.0 (from fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/41/e4/9de71dc666485c921f5c8d2d8078109af1f3925bf52f17ccf4c7cc19a8a0/pytest-3.4.0-py2.py3-none-any.whl
Collecting stdlib-list==0.4.0 (from fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/41/38/56992f4afe91c26bf78d4d9d37e10f5c8291a4a206063a945bac77d505c1/stdlib_list-0.4.0-py2.py3-none-any.whl
Collecting coverage>=3.7.1 (from pytest-cov==2.5.1->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/be/88/7e5e548329eda1f003b3ff34e57ba6b2b1f8b8983043e99a0ecf58ae0a06/coverage-4.5.2-cp37-cp37m-macosx_10_13_x86_64.whl
Collecting pytz>=0a (from Babel==2.5.3->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting requests>=2.7.9 (from codecov==2.0.15->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting gitdb>=0.6.4 (from GitPython==2.0.8->fiasko_bro)
Collecting attrs>=17.2.0 (from pytest==3.4.0->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest==3.4.0->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/3e/c7/3da685ef117d42ac8d71af525208759742dd235f8094221fdaafcd3dba8f/py-1.7.0-py2.py3-none-any.whl
Collecting pluggy<0.7,>=0.5 (from pytest==3.4.0->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/ba/65/ded3bc40bbf8d887f262f150fbe1ae6637765b5c9534bd55690ed2c0b0f7/pluggy-0.6.0-py3-none-any.whl
Collecting six>=1.10.0 (from pytest==3.4.0->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting setuptools (from pytest==3.4.0->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/bf/ae/a23db1762646069742cc21393833577d3fa438eecaa59d11fb04fa57fcd5/setuptools-40.7.1-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.7.9->codecov==2.0.15->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.7.9->codecov==2.0.15->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.7.9->codecov==2.0.15->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.7.9->codecov==2.0.15->fiasko_bro)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting smmap>=0.8.5 (from gitdb>=0.6.4->GitPython==2.0.8->fiasko_bro)
Installing collected packages: pep8, mccabe, attrs, py, pluggy, six, setuptools, pytest, coverage, pytest-cov, pytz, Babel, idna, chardet, urllib3, certifi, requests, codecov, smmap, gitdb, GitPython, stdlib-list, fiasko-bro
  Found existing installation: pep8 1.7.1
    Uninstalling pep8-1.7.1:
      Successfully uninstalled pep8-1.7.1
  Found existing installation: mccabe 0.6.1
    Uninstalling mccabe-0.6.1:
      Successfully uninstalled mccabe-0.6.1
  Found existing installation: attrs 18.2.0
    Uninstalling attrs-18.2.0:
      Successfully uninstalled attrs-18.2.0
  Found existing installation: py 1.7.0
    Uninstalling py-1.7.0:
      Successfully uninstalled py-1.7.0
  Found existing installation: pluggy 0.6.0
    Uninstalling pluggy-0.6.0:
      Successfully uninstalled pluggy-0.6.0
  Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
      Successfully uninstalled six-1.12.0
  Found existing installation: setuptools 40.7.1
    Uninstalling setuptools-40.7.1:
      Successfully uninstalled setuptools-40.7.1
  Found existing installation: pytest 3.4.0
    Uninstalling pytest-3.4.0:
      Successfully uninstalled pytest-3.4.0
  Found existing installation: coverage 4.5.2
    Uninstalling coverage-4.5.2:
      Successfully uninstalled coverage-4.5.2
  Found existing installation: pytest-cov 2.5.1
    Uninstalling pytest-cov-2.5.1:
      Successfully uninstalled pytest-cov-2.5.1
  Found existing installation: pytz 2018.9
    Uninstalling pytz-2018.9:
      Successfully uninstalled pytz-2018.9
  Found existing installation: Babel 2.5.3
    Uninstalling Babel-2.5.3:
      Successfully uninstalled Babel-2.5.3
  Found existing installation: idna 2.8
    Uninstalling idna-2.8:
      Successfully uninstalled idna-2.8
  Found existing installation: chardet 3.0.4
    Uninstalling chardet-3.0.4:
      Successfully uninstalled chardet-3.0.4
  Found existing installation: urllib3 1.24.1
    Uninstalling urllib3-1.24.1:
      Successfully uninstalled urllib3-1.24.1
  Found existing installation: certifi 2018.11.29
    Uninstalling certifi-2018.11.29:
      Successfully uninstalled certifi-2018.11.29
  Found existing installation: requests 2.21.0
    Uninstalling requests-2.21.0:
      Successfully uninstalled requests-2.21.0
  Found existing installation: codecov 2.0.15
    Uninstalling codecov-2.0.15:
      Successfully uninstalled codecov-2.0.15
  Found existing installation: smmap 0.9.0
    Uninstalling smmap-0.9.0:
      Successfully uninstalled smmap-0.9.0
  Found existing installation: gitdb 0.6.4
    Uninstalling gitdb-0.6.4:
      Successfully uninstalled gitdb-0.6.4
  Found existing installation: GitPython 2.0.8
    Uninstalling GitPython-2.0.8:
      Successfully uninstalled GitPython-2.0.8
  Found existing installation: stdlib-list 0.4.0
    Uninstalling stdlib-list-0.4.0:
      Successfully uninstalled stdlib-list-0.4.0
  Found existing installation: Fiasko-Bro 0.0.1.1
    Uninstalling Fiasko-Bro-0.0.1.1:
      Successfully uninstalled Fiasko-Bro-0.0.1.1
Successfully installed Babel-2.5.3 GitPython-2.0.8 attrs-18.2.0 certifi-2018.11.29 chardet-3.0.4 codecov-2.0.15 coverage-4.5.2 fiasko-bro-0.0.1.1 gitdb-0.6.4 idna-2.8 mccabe-0.6.1 pep8-1.7.1 pluggy-0.6.0 py-1.7.0 pytest-3.4.0 pytest-cov-2.5.1 pytz-2018.9 requests-2.21.0 setuptools-40.7.1 six-1.12.0 smmap-0.9.0 stdlib-list-0.4.0 urllib3-1.24.1
```

**Comment by vvscode** [comment]
On installation from github ( not from pip )

```
pip3 install git+https://github.com/devmanorg/fiasko_bro
Collecting git+https://github.com/devmanorg/fiasko_bro
  Cloning https://github.com/devmanorg/fiasko_bro to /private/var/folders/kk/fjvm63hn4mjb_k3qhtxxxz180000gn/T/pip-req-build-dae5o4eo
Requirement already satisfied: gitdb2==2.0.3 in /usr/local/lib/python3.7/site-packages (from Fiasko-Bro==0.0.1.1) (2.0.3)
Collecting gitpython==2.1.9 (from Fiasko-Bro==0.0.1.1)
  Using cached https://files.pythonhosted.org/packages/88/9c/b462dddb492204417f88d538b0931e87631f2a98afe89842929f4ed9ca5b/GitPython-2.1.9-py2.py3-none-any.whl
Requirement already satisfied: mccabe==0.6.1 in /usr/local/lib/python3.7/site-packages (from Fiasko-Bro==0.0.1.1) (0.6.1)
Requirement already satisfied: pep8==1.7.1 in /usr/local/lib/python3.7/site-packages (from Fiasko-Bro==0.0.1.1) (1.7.1)
Requirement already satisfied: smmap2==2.0.3 in /usr/local/lib/python3.7/site-packages (from Fiasko-Bro==0.0.1.1) (2.0.3)
Requirement already satisfied: stdlib-list==0.4.0 in /usr/local/lib/python3.7/site-packages (from Fiasko-Bro==0.0.1.1) (0.4.0)
Building wheels for collected packages: Fiasko-Bro
  Running setup.py bdist_wheel for Fiasko-Bro ... done
  Stored in directory: /private/var/folders/kk/fjvm63hn4mjb_k3qhtxxxz180000gn/T/pip-ephem-wheel-cache-8n6ossq_/wheels/80/07/61/1509bf320f6693e6c25b361a44e36eed632d9e59fdee5d017f
Successfully built Fiasko-Bro
Installing collected packages: gitpython, Fiasko-Bro
  Found existing installation: GitPython 2.0.8
    Uninstalling GitPython-2.0.8:
      Successfully uninstalled GitPython-2.0.8
Successfully installed Fiasko-Bro-0.0.1.1 gitpython-2.1.9
vvscode@MacBook-Pro-vvscode ~/r/d/12_image_resize> fiasko
/usr/local/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Traceback (most recent call last):
  File "/usr/local/bin/fiasko", line 7, in <module>
    from bin.fiasko import main
  File "/usr/local/lib/python3.7/site-packages/bin/fiasko.py", line 5, in <module>
    from fiasko_bro.configparser_helpers import extract_fiasko_config_from_cfg_file
ModuleNotFoundError: No module named 'fiasko_bro.configparser_helpers'
```
