### ISSUE TITLE
Gracefully handling syntax errors in repos

### ISSUE THREAD

**Issue by Askanio234** [devmanorg/fiasko_bro#80]
Currently if repository has any syntax errors user will get an exception. 
```
>>> import fiasko_bro
>>> fiasko_bro.validate_repo("/home/askanio/Documents/Projects/test_for_fiasko_with_syntax_error")
invalid syntax (<unknown>, line 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/askanio/Documents/Projects/fiasko_bro/fiasko_bro/code_validator.py", line 16, in validate_repo
    return code_validator.validate(path_to_repo, path_to_original_repo, **kwargs)
  File "/home/askanio/Documents/Projects/fiasko_bro/fiasko_bro/code_validator.py", line 161, in validate
    return self.run_validator_group(self.error_validator_groups, add_warnings=True)
  File "/home/askanio/Documents/Projects/fiasko_bro/fiasko_bro/code_validator.py", line 139, in run_validator_group
    self.validator_arguments
  File "/home/askanio/Documents/Projects/fiasko_bro/fiasko_bro/code_validator.py", line 117, in _run_validator_group
    validation_result = validator(**arguments)
  File "/home/askanio/Documents/Projects/fiasko_bro/fiasko_bro/validators/naming.py", line 42, in is_snake_case
    names = ast_helpers.get_all_names_from_tree(tree)
  File "/home/askanio/Documents/Projects/fiasko_bro/fiasko_bro/ast_helpers.py", line 21, in get_all_names_from_tree
    return list({node.id for node in ast.walk(tree) if isinstance(node, ast.Name)})
  File "/home/askanio/Documents/Projects/fiasko_bro/fiasko_bro/ast_helpers.py", line 21, in <setcomp>
    return list({node.id for node in ast.walk(tree) if isinstance(node, ast.Name)})
  File "/usr/lib/python3.5/ast.py", line 217, in walk
    todo.extend(iter_child_nodes(node))
  File "/usr/lib/python3.5/ast.py", line 182, in iter_child_nodes
    for name, field in iter_fields(node):
  File "/usr/lib/python3.5/ast.py", line 170, in iter_fields
    for field in node._fields:
AttributeError: 'NoneType' object has no attribute '_fields'
```
I think it is better to add syntax check to the pre_validation_checks. As far as i understand current syntax validator will not function properly anyway. Whats the best way to check repository for syntax errors though? (Before LocalRepositoryInfo object is created).

**Comment by Askanio234** [comment]
Or maybe we should deal with it in ```LocalRepositoryInfo``` class
